version: '3.8'

services:
  postgres:
    container_name: postgres_directory_service
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: directory_service_db
      POSTGRES_USER: mag63669
      POSTGRES_PASSWORD: 6369
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - directory-network

  seq:
    image: datalust/seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"   
      - "8081:80"     
    volumes:
      - seq-data:/data
    networks:
      - directory-network
    depends_on:
      - postgres

volumes:
  postgres-data:
  seq-data:

networks:
  directory-network:
    driver: bridge