services:
  postgres:
    container_name: postgres_directory_service
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: directory_service_db
      POSTGRES_USER: mag63669
      POSTGRES_PASSWORD: 6369
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: